version: '3'

services:
  apilama-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    volumes:
      - ./tests:/app/tests
      - ./test-reports:/app/test-reports
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=True
      - PYBOX_URL=http://pybox-mock:8001
      - PYLLM_URL=http://pyllm-mock:8002
    depends_on:
      - pybox-mock
      - pyllm-mock
    command: |
      bash -c "python -m pytest tests/ -v --junitxml=/app/test-reports/test-results.xml"

  apilama-mock:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    volumes:
      - ./tests:/app/tests
      - ./test-reports:/app/test-reports
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=True
      - MOCK_MODE=true
      - PYBOX_URL=http://pybox-mock:8001
      - PYLLM_URL=http://pyllm-mock:8002
    depends_on:
      - pybox-mock
      - pyllm-mock
    command: |
      bash -c "python -m apilama.app --port 8080 --host 0.0.0.0"

  pybox-mock:
    build:
      context: ../pybox
      dockerfile: Dockerfile.test
    ports:
      - "8001:8001"
    volumes:
      - ../pybox/tests:/app/tests
      - ../pybox/test-reports:/app/test-reports
    environment:
      - PORT=8001
      - HOST=0.0.0.0
      - DEBUG=True
      - MOCK_MODE=true
    command: |
      bash -c "python -m pybox.app --port 8001 --host 0.0.0.0"

  pyllm-mock:
    build:
      context: ../pyllm
      dockerfile: Dockerfile.test
    ports:
      - "8002:8002"
    volumes:
      - ../pyllm/tests:/app/tests
      - ../pyllm/test-reports:/app/test-reports
    environment:
      - PORT=8002
      - HOST=0.0.0.0
      - DEBUG=True
      - MOCK_MODE=true
    command: |
      bash -c "python -m pyllm.app --port 8002 --host 0.0.0.0"

volumes:
  test-reports:
